import { describe, it } from 'vitest'
import * as assert from 'assert'
import { parseStackTrace } from './parseStackTrace'

describe('parseStackTrace', function () {
  it('base', function () {
    const stackTrace = `Error
message
at f1 (file:///file1.js:2:17)
  at f2 (file2.js:2)
    at f3 (file3.js)
\tat f4 (<anonymous>:2:17)
\t\tat f5 (<anonymous>:2)
      at f6 (<anonymous>)
      at <anonymous>:2:17
      at <anonymous>:2
      at <anonymous>
      at file1.js:2:17
      at file2.js:2
      at http://localhost:3000/file3.js:2:17
      at http://localhost:3000:2:17
      at f7 (http://localhost:3000:2:17)
      at (file8.js:2:17)
      at (file9.js:2)
      at (file10.js)
`

    const frames = parseStackTrace(stackTrace)

    assert.deepStrictEqual(frames, [
      { func: 'f1', file: 'file:///file1.js', line: 2, column: 17 },
      { func: 'f2', file: 'file2.js', line: 2, column: void 0 },
      { func: 'f3', file: 'file3.js', line: void 0, column: void 0 },
      { func: 'f4', file: '<anonymous>', line: 2, column: 17 },
      { func: 'f5', file: '<anonymous>', line: 2, column: void 0 },
      { func: 'f6', file: '<anonymous>', line: void 0, column: void 0 },
      { func: void 0, file: '<anonymous>', line: 2, column: 17 },
      { func: void 0, file: '<anonymous>', line: 2, column: void 0 },
      { func: '<anonymous>', file: void 0, line: void 0, column: void 0 },
      { func: void 0, file: 'file1.js', line: 2, column: 17 },
      { func: void 0, file: 'file2.js', line: 2, column: void 0 },
      {
        func: void 0,
        file: 'http://localhost:3000/file3.js',
        line: 2,
        column: 17,
      },
      { func: void 0, file: 'http://localhost:3000', line: 2, column: 17 },
      { func: 'f7', file: 'http://localhost:3000', line: 2, column: 17 },
      { func: void 0, file: 'file8.js', line: 2, column: 17 },
      { func: void 0, file: 'file9.js', line: 2, column: void 0 },
      { func: void 0, file: 'file10.js', line: void 0, column: void 0 },
    ])

    // console.log(frames)
  })

  it('generated by chat gpt', function () {
    const stackTrace = `
      at Object.functionName (file:///path/to/your/script.js:10:15)
      at functionName (http://www.example.com/script.js:5:3)
      at functionName (https://www.example.com/scripts/index.js:27:7)
      at /path/to/your/script.js:11:8
      at http://www.example.com/script.js:8:2
      at https://www.example.com/scripts/index.js:34:5
      at new ClassName (file:///path/to/your/class.js:30:20)
      at ClassName.methodName (file:///path/to/your/class.js:44:12)
      at ClassName.prototype.methodName (file:///path/to/your/class.js:54:10)
      at Promise.resolve.then (file:///path/to/your/asyncFunction.js:21:25)
      at process._tickCallback (internal/process/next_tick.js:68:7)
      at Module.runMain (module.js:678:11)
      at startup (bootstrap_node.js:187:16)
      at bootstrap_node.js:608:3
      at functionName [as aliasName] (file:///path/to/your/script.js:10:5)
      at /path/to/your/anonymousFunction.js:4:11
      at http://www.example.com:8080/script.js:15:3
      at functionName (/path/to/your/node_modules/module_name/index.js:12:10)
      at file:///path/to/your/inlineScript.html:10:15
      at async functionName (file:///path/to/your/asyncFunction.js:7:9)
      at functionName (/path/to/your/node_modules/module_name/lib/utils.js:8:15)
      at functionName (blob:http://www.example.com/1234abcd-1234-1234-1234-1234abcd5678:4:7)
      at functionName (webpack:///./src/your/webpackedScript.js:10:15)
      at Function.functionName (native)
      at functionName (unknown source)
`

    // at eval (eval at functionName (file:///path/to/your/script.js:22:5), <anonymous>:1:1)
    // at /path/to/your/evalFunction.js:3:3 (eval at functionName (file:///path/to/your/script.js:22:5))
    // at /path/to/your/lambdaFunction.js:7:11 (Lambda@Edge)

    const frames = parseStackTrace(stackTrace)

    assert.deepStrictEqual(frames, [
      {
        func: 'Object.functionName',
        file: 'file:///path/to/your/script.js',
        line: 10,
        column: 15,
      },
      {
        func: 'functionName',
        file: 'http://www.example.com/script.js',
        line: 5,
        column: 3,
      },
      {
        func: 'functionName',
        file: 'https://www.example.com/scripts/index.js',
        line: 27,
        column: 7,
      },
      { func: void 0, file: '/path/to/your/script.js', line: 11, column: 8 },
      {
        func: void 0,
        file: 'http://www.example.com/script.js',
        line: 8,
        column: 2,
      },
      {
        func: void 0,
        file: 'https://www.example.com/scripts/index.js',
        line: 34,
        column: 5,
      },
      {
        func: 'new ClassName',
        file: 'file:///path/to/your/class.js',
        line: 30,
        column: 20,
      },
      {
        func: 'ClassName.methodName',
        file: 'file:///path/to/your/class.js',
        line: 44,
        column: 12,
      },
      {
        func: 'ClassName.prototype.methodName',
        file: 'file:///path/to/your/class.js',
        line: 54,
        column: 10,
      },
      {
        func: 'Promise.resolve.then',
        file: 'file:///path/to/your/asyncFunction.js',
        line: 21,
        column: 25,
      },
      {
        func: 'process._tickCallback',
        file: 'internal/process/next_tick.js',
        line: 68,
        column: 7,
      },
      { func: 'Module.runMain', file: 'module.js', line: 678, column: 11 },
      { func: 'startup', file: 'bootstrap_node.js', line: 187, column: 16 },
      { func: void 0, file: 'bootstrap_node.js', line: 608, column: 3 },
      {
        func: 'functionName [as aliasName]',
        file: 'file:///path/to/your/script.js',
        line: 10,
        column: 5,
      },
      {
        func: void 0,
        file: '/path/to/your/anonymousFunction.js',
        line: 4,
        column: 11,
      },
      {
        func: void 0,
        file: 'http://www.example.com:8080/script.js',
        line: 15,
        column: 3,
      },
      {
        func: 'functionName',
        file: '/path/to/your/node_modules/module_name/index.js',
        line: 12,
        column: 10,
      },
      {
        func: void 0,
        file: 'file:///path/to/your/inlineScript.html',
        line: 10,
        column: 15,
      },
      {
        func: 'async functionName',
        file: 'file:///path/to/your/asyncFunction.js',
        line: 7,
        column: 9,
      },
      {
        func: 'functionName',
        file: '/path/to/your/node_modules/module_name/lib/utils.js',
        line: 8,
        column: 15,
      },
      {
        func: 'functionName',
        file: 'blob:http://www.example.com/1234abcd-1234-1234-1234-1234abcd5678',
        line: 4,
        column: 7,
      },
      {
        func: 'functionName',
        file: 'webpack:///./src/your/webpackedScript.js',
        line: 10,
        column: 15,
      },
      {
        func: 'Function.functionName',
        file: 'native',
        line: void 0,
        column: void 0,
      },
      {
        func: 'functionName',
        file: 'unknown source',
        line: void 0,
        column: void 0,
      },
    ])
  })

  it('generated by chat gpt 2', function () {
    const stackTrace = `
      at exampleFunction (/path/to/file.js:12:34)
      at Object.<anonymous> (/path/to/file.js:12:34)
      at /path/to/file.js:12:34
      at <anonymous>:12:34
      at exampleFunction (http://example.com/path/to/file.js:12:34)
      at Object.<anonymous> (http://example.com/path/to/file.js:12:34)
      at http://example.com/path/to/file.js:12:34
      at <anonymous>:12:34
      at exampleFunction (/path/to/file.js:12)
      at exampleFunction (/path/to/file.js)
      at exampleFunction (/path/to/file.js:12:34)
      at Object.<anonymous> (/path/to/file.js:12)
      at Object.<anonymous> (/path/to/file.js)
      at Object.<anonymous> (/path/to/file.js:12:34)
      at /path/to/file.js:12
      at /path/to/file.js:12:34
      at <anonymous> (/path/to/file.js:12)
      at <anonymous> (/path/to/file.js)
      at <anonymous> (/path/to/file.js:12:34)
`

    // at /path/to/file.js

    const frames = parseStackTrace(stackTrace)

    assert.deepStrictEqual(frames, [
      {
        func: 'exampleFunction',
        file: '/path/to/file.js',
        line: 12,
        column: 34,
      },
      {
        func: 'Object.<anonymous>',
        file: '/path/to/file.js',
        line: 12,
        column: 34,
      },
      { func: void 0, file: '/path/to/file.js', line: 12, column: 34 },
      { func: void 0, file: '<anonymous>', line: 12, column: 34 },
      {
        func: 'exampleFunction',
        file: 'http://example.com/path/to/file.js',
        line: 12,
        column: 34,
      },
      {
        func: 'Object.<anonymous>',
        file: 'http://example.com/path/to/file.js',
        line: 12,
        column: 34,
      },
      {
        func: void 0,
        file: 'http://example.com/path/to/file.js',
        line: 12,
        column: 34,
      },
      { func: void 0, file: '<anonymous>', line: 12, column: 34 },
      {
        func: 'exampleFunction',
        file: '/path/to/file.js',
        line: 12,
        column: void 0,
      },
      {
        func: 'exampleFunction',
        file: '/path/to/file.js',
        line: void 0,
        column: void 0,
      },
      {
        func: 'exampleFunction',
        file: '/path/to/file.js',
        line: 12,
        column: 34,
      },
      {
        func: 'Object.<anonymous>',
        file: '/path/to/file.js',
        line: 12,
        column: void 0,
      },
      {
        func: 'Object.<anonymous>',
        file: '/path/to/file.js',
        line: void 0,
        column: void 0,
      },
      {
        func: 'Object.<anonymous>',
        file: '/path/to/file.js',
        line: 12,
        column: 34,
      },
      { func: void 0, file: '/path/to/file.js', line: 12, column: void 0 },
      { func: void 0, file: '/path/to/file.js', line: 12, column: 34 },
      {
        func: '<anonymous>',
        file: '/path/to/file.js',
        line: 12,
        column: void 0,
      },
      {
        func: '<anonymous>',
        file: '/path/to/file.js',
        line: void 0,
        column: void 0,
      },
      { func: '<anonymous>', file: '/path/to/file.js', line: 12, column: 34 },
    ])
  })
})
