/** Generated by AI only */
import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { Cache, type CacheOptions } from 'src/common/cache/Cache'
import type { CacheStat, IStorage, IStorageDb } from 'src/common/cache/types'
import { createFileCacheOptions } from './createFileCacheOptions'
import * as fs from 'fs'
import * as path from 'path'
import type { NumberRange } from 'src/common/types/common'
import type { ConvertToAsync } from 'src/common/converter/types'
import { TimeControllerMock } from '@flemist/time-controller'
import { waitMicrotasks, waitTimeControllerMock } from '@flemist/async-utils'
import {
  decompressGzip,
  isGzipCompressed,
} from 'src/common/gzip/decompressGzip'

const DIR_TMP = '-tmp/-test/cache'
const DIR_CACHE = DIR_TMP + '/cache'
const DIR_CACHE_TMP = DIR_TMP + '/tmp'

describe('Cache', () => {
  describe('getOrCreate', () => {
    it('base', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      let callCount = 0
      const result = await cache.getOrCreate('key1', input => {
        expect(input).toBe('key1')
        callCount++
        return 'value1'
      })
      expect(result).toBe('value1')
      expect(callCount).toBe(1)

      expect(Array.from(t.storages.value.data.entries())).toEqual([
        ['key1', 'value1'],
      ])
      expect(Array.from(t.storages.error.data.entries())).toEqual([])
      const stat = t.storages.stat.data.get('key1')!
      expect(stat.size).toBe('value1'.length + 1)
      expect(stat.hasError).toBeUndefined()
      expect(stat.dateModified).toBe(stat.dateUsed)

      // Second call with same key returns cached value without calling func
      const result2 = await cache.getOrCreate('key1', () => {
        callCount++
        return 'value1-new'
      })
      expect(result2).toBe('value1')
      expect(callCount).toBe(1)

      // Different key calls func
      const result3 = await cache.getOrCreate('key2', input => {
        expect(input).toBe('key2')
        callCount++
        return 'value2'
      })
      expect(result3).toBe('value2')
      expect(callCount).toBe(2)

      expect(t.storages.value.data.size).toBe(2)
      expect(t.storages.error.data.size).toBe(0)
      expect(t.storages.stat.data.size).toBe(2)
    })

    it('caches errors', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      // Use string error for proper size tracking in memory storage
      let callCount = 0

      await expect(
        cache.getOrCreate('key1', () => {
          callCount++
          throw 'test-error-string'
        }),
      ).rejects.toBe('test-error-string')
      expect(callCount).toBe(1)

      // Second call returns cached error without calling func
      await expect(
        cache.getOrCreate('key1', () => {
          callCount++
          return 'value1'
        }),
      ).rejects.toBe('test-error-string')
      expect(callCount).toBe(1)

      // Verify error is stored, value is not
      expect(t.storages.value.data.has('key1')).toBe(false)
      expect(t.storages.error.data.has('key1')).toBe(true)
      expect(t.storages.error.data.get('key1')).toBe('test-error-string')

      const stat = t.storages.stat.data.get('key1')!
      expect(stat.hasError).toBe(true)
      expect(stat.size).toBe('test-error-string'.length + 1)
    })

    it('updates dateUsed on cache hit', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({ timeController: tc })
      const cache = createCache(t)

      await cache.getOrCreate('key1', () => 'value1')
      const statAfterCreate = t.storages.stat.data.get('key1')!
      expect(statAfterCreate.dateModified).toBe(1000)
      expect(statAfterCreate.dateUsed).toBe(1000)

      tc.setTime(2000)
      await cache.getOrCreate('key1', () => 'value1-new')
      const statAfterHit = t.storages.stat.data.get('key1')!
      expect(statAfterHit.dateModified).toBe(1000)
      expect(statAfterHit.dateUsed).toBe(2000)
    })

    it('updates dateUsed on cached error hit', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({ timeController: tc })
      const cache = createCache(t)

      await expect(
        cache.getOrCreate('key1', () => {
          throw 'cached-error'
        }),
      ).rejects.toBe('cached-error')

      tc.setTime(2000)
      await expect(cache.getOrCreate('key1', () => 'value1')).rejects.toBe(
        'cached-error',
      )
      const stat = t.storages.stat.data.get('key1')!
      expect(stat.dateModified).toBe(1000)
      expect(stat.dateUsed).toBe(2000)
      expect(stat.hasError).toBe(true)
    })

    it('re-computes when stat exists but stored data is missing', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      await cache.getOrCreate('key1', () => 'value1')

      // Simulate corrupt state: stat exists but value deleted externally
      t.storages.value.data.delete('key1')

      let callCount = 0
      const result = await cache.getOrCreate('key1', () => {
        callCount++
        return 'value1-recomputed'
      })
      expect(result).toBe('value1-recomputed')
      expect(callCount).toBe(1)
    })

    it('re-computes when stat exists with hasError but error data is missing', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      await expect(
        cache.getOrCreate('key1', () => {
          throw 'some-error'
        }),
      ).rejects.toBe('some-error')

      // Simulate corrupt state: stat with hasError but error deleted externally
      t.storages.error.data.delete('key1')

      let callCount = 0
      const result = await cache.getOrCreate('key1', () => {
        callCount++
        return 'value1-recomputed'
      })
      expect(result).toBe('value1-recomputed')
      expect(callCount).toBe(1)
    })

    it('func receives original input when converterInput is set', async () => {
      const t = createTestOptions()
      t.options.converterInput = ((input: string) =>
        'converted-' + input) as ConvertToAsync<string, string>
      const cache = createCache(t)

      const receivedInputs: string[] = []
      await cache.getOrCreate('original', input => {
        receivedInputs.push(input)
        return 'value'
      })
      expect(receivedInputs).toEqual(['original'])

      // Verify stored under converted key
      expect(t.storages.value.data.has('converted-original')).toBe(true)
      expect(t.storages.value.data.has('original')).toBe(false)
    })

    it('converterInput maps different inputs to same key', async () => {
      const t = createTestOptions()
      t.options.converterInput = ((input: string) =>
        input.toLowerCase()) as ConvertToAsync<string, string>
      const cache = createCache(t)

      let callCount = 0
      await cache.getOrCreate('ABC', () => {
        callCount++
        return 'value1'
      })
      const result = await cache.getOrCreate('abc', () => {
        callCount++
        return 'value2'
      })
      expect(result).toBe('value1')
      expect(callCount).toBe(1)
      expect(t.storages.value.data.size).toBe(1)
    })

    it('converterValue transforms stored values', async () => {
      const t = createTestOptions()
      t.options.converterValue = {
        to: (value: string) => 'stored:' + value,
        from: (stored: string) => stored.replace('stored:', ''),
      }
      const cache = createCache(t)

      await cache.getOrCreate('key1', () => 'value1')
      expect(t.storages.value.data.get('key1')).toBe('stored:value1')

      const result = await cache.getOrCreate('key1', () => 'value2')
      expect(result).toBe('value1')
    })

    it('converterError transforms stored errors', async () => {
      const t = createTestOptions()
      t.options.converterError = {
        to: (error: any) => 'stored-error:' + String(error),
        from: (stored: string) => stored.replace('stored-error:', ''),
      }
      const cache = createCache(t)

      await expect(
        cache.getOrCreate('key1', () => {
          throw 'original-err'
        }),
      ).rejects.toBe('original-err')

      expect(t.storages.error.data.get('key1')).toBe(
        'stored-error:original-err',
      )

      // Second call retrieves converted error
      await expect(cache.getOrCreate('key1', () => 'value')).rejects.toBe(
        'original-err',
      )
    })

    it('stat.size includes both data size and stat overhead', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      await cache.getOrCreate('key1', () => 'hello') // value 5 + stat 1 = 6
      expect(t.storages.stat.data.get('key1')!.size).toBe(6)

      await expect(
        cache.getOrCreate('key2', () => {
          throw 'err'
        }),
      ).rejects.toBe('err')
      const errStat = t.storages.stat.data.get('key2')!
      expect(errStat.size).toBe(4) // error 'err' = 3 + stat 1 = 4
      expect(errStat.hasError).toBe(true)
    })
  })

  describe('expiration', () => {
    it('re-computes expired entries', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({
        timeController: tc,
        isExpired: stat => tc.now() - stat.dateModified > 500,
      })
      const cache = createCache(t)

      await cache.getOrCreate('key1', () => 'value1')

      // Not expired yet
      tc.setTime(1400)
      const result1 = await cache.getOrCreate('key1', () => 'value2')
      expect(result1).toBe('value1')

      // Expired
      tc.setTime(1600)
      let callCount = 0
      const result2 = await cache.getOrCreate('key1', () => {
        callCount++
        return 'value3'
      })
      expect(result2).toBe('value3')
      expect(callCount).toBe(1)

      expect(t.storages.value.data.get('key1')).toBe('value3')
    })

    it('cleans up old storage entries on expiration', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({
        timeController: tc,
        isExpired: stat => tc.now() - stat.dateModified > 500,
      })
      const cache = createCache(t)

      // Store an error
      await expect(
        cache.getOrCreate('key1', () => {
          throw 'old-error'
        }),
      ).rejects.toBe('old-error')

      expect(t.storages.error.data.has('key1')).toBe(true)

      // Expire and re-compute with a value
      tc.setTime(2000)
      await cache.getOrCreate('key1', () => 'new-value')

      // Error storage should be cleaned, value should be set
      expect(t.storages.error.data.has('key1')).toBe(false)
      expect(t.storages.value.data.get('key1')).toBe('new-value')
      expect(t.storages.stat.data.get('key1')!.hasError).toBeUndefined()
    })

    it('expired error entry gets re-computed', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({
        timeController: tc,
        isExpired: stat => tc.now() - stat.dateModified > 500,
      })
      const cache = createCache(t)

      await expect(
        cache.getOrCreate('key1', () => {
          throw 'old-error'
        }),
      ).rejects.toBe('old-error')

      tc.setTime(2000)
      const result = await cache.getOrCreate('key1', () => 'fresh-value')
      expect(result).toBe('fresh-value')
    })

    it('expiration checks dateModified not dateUsed', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({
        timeController: tc,
        isExpired: stat => tc.now() - stat.dateModified > 500,
      })
      const cache = createCache(t)

      await cache.getOrCreate('key1', () => 'value1')

      // Access at now=1400 to update dateUsed
      tc.setTime(1400)
      await cache.getOrCreate('key1', () => 'should-not-compute')
      expect(t.storages.stat.data.get('key1')!.dateUsed).toBe(1400)

      // At now=1600, dateModified=1000, age=600 > 500, expired despite recent access
      tc.setTime(1600)
      let callCount = 0
      await cache.getOrCreate('key1', () => {
        callCount++
        return 'recomputed'
      })
      expect(callCount).toBe(1)
    })
  })

  describe('totalSize and LRU eviction', () => {
    it('evicts LRU entries and cleans down to min', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      // min=20 prevents over-eviction: after evicting key1, totalSize=22
      // removing key2 (size 11) would bring total to 11 < 20, so stop
      const t = createTestOptions({
        timeController: tc,
        totalSize: [20, 30],
      })
      const cache = createCache(t)

      tc.setTime(1000)
      await cache.getOrCreate('key1', () => 'aaaaaaaaaa') // size 11, total 11
      tc.setTime(2000)
      await cache.getOrCreate('key2', () => 'bbbbbbbbbb') // size 11, total 22

      expect(t.storages.value.data.size).toBe(2)

      // Adding key3: 22 + 11 = 33 > 30
      // Evict key1 (LRU dateUsed=1000): totalSize=22
      // key2: 22-11=11 < 20, stop
      tc.setTime(3000)
      await cache.getOrCreate('key3', () => 'cccccccccc')

      expect(t.storages.value.data.has('key1')).toBe(false)
      expect(t.storages.value.data.has('key2')).toBe(true)
      expect(t.storages.value.data.has('key3')).toBe(true)
      expect(t.storages.stat.data.has('key1')).toBe(false)
    })

    it('aggressively evicts down to min when min is low', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({
        timeController: tc,
        totalSize: [0, 30],
      })
      const cache = createCache(t)

      tc.setTime(1000)
      await cache.getOrCreate('key1', () => 'aaaaaaaaaa') // size 11, total 11
      tc.setTime(2000)
      await cache.getOrCreate('key2', () => 'bbbbbbbbbb') // size 11, total 22

      // Adding key3: total 33 > 30
      // Evict key1: totalSize=22, 22-11=11 > 0, evict key2 too
      // key2 evicted: totalSize=11, 11-11=0 NOT > 0, stop
      tc.setTime(3000)
      await cache.getOrCreate('key3', () => 'cccccccccc')

      expect(t.storages.value.data.has('key1')).toBe(false)
      expect(t.storages.value.data.has('key2')).toBe(false)
      expect(t.storages.value.data.has('key3')).toBe(true)
      expect(t.storages.stat.data.size).toBe(1)
    })

    it('throws when single entry exceeds totalSize max', async () => {
      const t = createTestOptions({ totalSize: [0, 5] })
      const cache = createCache(t)

      // value 'abcdef' = 6 chars + stat 1 = 7 > 5
      await expect(cache.getOrCreate('key1', () => 'abcdef')).rejects.toThrow(
        /value size.*exceeds maximum total size/,
      )

      // Storage should remain clean after failed insertion
      expect(t.storages.value.data.size).toBe(0)
      expect(t.storages.stat.data.size).toBe(0)
    })

    it('respects totalSize minimum during eviction', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({
        timeController: tc,
        totalSize: [15, 25],
      })
      const cache = createCache(t)

      tc.setTime(1000)
      await cache.getOrCreate('key1', () => 'aaaaaaaaa') // size 10, total 10
      tc.setTime(2000)
      await cache.getOrCreate('key2', () => 'bbbbbbbbb') // size 10, total 20

      // Adding key3 (size 10): total 30 > 25
      // Evict key1 (LRU): totalSize=20, 20-10=10 < 15, stop
      // key2 survives
      tc.setTime(3000)
      await cache.getOrCreate('key3', () => 'ccccccccc')

      expect(t.storages.value.data.has('key1')).toBe(false)
      expect(t.storages.value.data.has('key2')).toBe(true)
      expect(t.storages.value.data.has('key3')).toBe(true)
    })

    it('condition 1 priority: evicts below min when necessary to fit new entry', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      // Entry sizes are 11 each, max=15
      // After storing key1 (11), storing key2 (11) makes total 22 > 15
      // Evicting key1 (11) makes total 11, and 11-11=0 < 10, but 11 <= 15
      // So eviction stops after key1 (condition 1 satisfied: 11 <= 15)
      const t = createTestOptions({
        timeController: tc,
        totalSize: [10, 15],
      })
      const cache = createCache(t)

      tc.setTime(1000)
      await cache.getOrCreate('key1', () => 'aaaaaaaaaa') // size 11

      tc.setTime(2000)
      await cache.getOrCreate('key2', () => 'bbbbbbbbbb') // size 11, total 22 > 15

      // key1 evicted, only key2 remains
      expect(t.storages.value.data.has('key1')).toBe(false)
      expect(t.storages.value.data.has('key2')).toBe(true)
    })

    it('evicts by dateUsed then by size then by dateModified then by key', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      // min=35: prevents evicting key-large after key-small and key-medium are gone
      const t = createTestOptions({
        timeController: tc,
        totalSize: [35, 50],
      })
      const cache = createCache(t)

      tc.setTime(1000)
      await cache.getOrCreate('key-large', () => 'x'.repeat(14)) // size 15
      await cache.getOrCreate('key-small', () => 'x'.repeat(4)) // size 5
      await cache.getOrCreate('key-medium', () => 'x'.repeat(9)) // size 10

      // All dateUsed=1000, sort by size ascending: small(5), medium(10), large(15)
      tc.setTime(2000)
      await cache.getOrCreate('key-new', () => 'x'.repeat(24)) // size 25, total 30+25=55

      // Evict small(5): 50, medium(10): 40, large(15): 40-15=25 < 35, stop
      expect(t.storages.value.data.has('key-small')).toBe(false)
      expect(t.storages.value.data.has('key-medium')).toBe(false)
      expect(t.storages.value.data.has('key-large')).toBe(true)
      expect(t.storages.value.data.has('key-new')).toBe(true)
    })

    it('LRU access updates eviction priority', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({
        timeController: tc,
        totalSize: [20, 30],
      })
      const cache = createCache(t)

      tc.setTime(1000)
      await cache.getOrCreate('key1', () => 'aaaaaaaaaa') // size 11, dateUsed=1000
      tc.setTime(2000)
      await cache.getOrCreate('key2', () => 'bbbbbbbbbb') // size 11, dateUsed=2000

      // Access key1 to update its dateUsed to 3000
      tc.setTime(3000)
      await cache.getOrCreate('key1', () => 'should-not-compute')
      expect(t.storages.stat.data.get('key1')!.dateUsed).toBe(3000)

      // Now key2 is LRU (dateUsed=2000 < key1 dateUsed=3000)
      tc.setTime(4000)
      await cache.getOrCreate('key3', () => 'cccccccccc')

      // key2 evicted (LRU), key1 and key3 survive
      expect(t.storages.value.data.has('key1')).toBe(true)
      expect(t.storages.value.data.has('key2')).toBe(false)
      expect(t.storages.value.data.has('key3')).toBe(true)
    })

    it('skips current key during eviction', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({
        timeController: tc,
        totalSize: [0, 25],
        isExpired: stat => tc.now() - stat.dateModified > 500,
      })
      const cache = createCache(t)

      tc.setTime(1000)
      await cache.getOrCreate('key1', () => 'aaaaaaaaaa') // size 11

      // Expire and re-compute with larger value
      // freeUpSpace receives currentKey='key1', skips it in eviction
      tc.setTime(2000)
      await cache.getOrCreate('key1', () => 'x'.repeat(14)) // size 15

      expect(t.storages.value.data.has('key1')).toBe(true)
      expect(t.storages.value.data.get('key1')).toBe('x'.repeat(14))
    })

    it('evicts error entries too', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({
        timeController: tc,
        totalSize: [10, 30],
      })
      const cache = createCache(t)

      tc.setTime(1000)
      await expect(
        cache.getOrCreate('key1', () => {
          throw 'cached-err'
        }),
      ).rejects.toBe('cached-err')
      const key1Size = t.storages.stat.data.get('key1')!.size
      expect(key1Size).toBe('cached-err'.length + 1)

      tc.setTime(2000)
      await cache.getOrCreate('key2', () => 'bbbbbbbbbb') // size 11

      // Adding key3 triggers eviction, key1 is LRU
      tc.setTime(3000)
      await cache.getOrCreate('key3', () => 'cccccccccc')

      expect(t.storages.stat.data.has('key1')).toBe(false)
      expect(t.storages.error.data.has('key1')).toBe(false)
    })

    it('no eviction when totalSize is null', async () => {
      const t = createTestOptions({ totalSize: null })
      const cache = createCache(t)

      for (let i = 0; i < 100; i++) {
        await cache.getOrCreate(`key${i}`, () => 'x'.repeat(1000))
      }
      expect(t.storages.value.data.size).toBe(100)
    })

    it('handles replacing cached value with error accounting for size', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({
        timeController: tc,
        isExpired: stat => tc.now() - stat.dateModified > 500,
        totalSize: [0, 30],
      })
      const cache = createCache(t)

      tc.setTime(1000)
      await cache.getOrCreate('key1', () => 'aaaaaaaaaa') // value 10 + stat 1 = 11

      // Expire and store error instead
      tc.setTime(2000)
      const errStr = 'x'.repeat(9) // 9 chars + stat 1 = 10
      await expect(
        cache.getOrCreate('key1', () => {
          throw errStr
        }),
      ).rejects.toBe(errStr)

      const stat = t.storages.stat.data.get('key1')!
      expect(stat.hasError).toBe(true)
      expect(stat.size).toBe(10)
      expect(t.storages.value.data.has('key1')).toBe(false)
      expect(t.storages.error.data.get('key1')).toBe(errStr)
    })
  })

  describe('delete', () => {
    it('removes value entry and allows re-computation', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      await cache.getOrCreate('key1', () => 'value1')
      expect(t.storages.value.data.has('key1')).toBe(true)

      await cache.delete('key1')

      expect(t.storages.value.data.has('key1')).toBe(false)
      expect(t.storages.error.data.has('key1')).toBe(false)
      expect(t.storages.stat.data.has('key1')).toBe(false)

      let callCount = 0
      const result = await cache.getOrCreate('key1', () => {
        callCount++
        return 'value2'
      })
      expect(result).toBe('value2')
      expect(callCount).toBe(1)
    })

    it('removes error entry and allows re-computation', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      await expect(
        cache.getOrCreate('key1', () => {
          throw 'cached-error'
        }),
      ).rejects.toBe('cached-error')

      await cache.delete('key1')

      const result = await cache.getOrCreate('key1', () => 'fresh')
      expect(result).toBe('fresh')
    })

    it('delete non-existent key does not throw', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      await cache.delete('non-existent')
    })

    it('uses converterInput for key resolution', async () => {
      const t = createTestOptions()
      t.options.converterInput = ((input: string) =>
        input.toUpperCase()) as ConvertToAsync<string, string>
      const cache = createCache(t)

      await cache.getOrCreate('abc', () => 'value1')
      expect(t.storages.value.data.has('ABC')).toBe(true)

      await cache.delete('abc')
      expect(t.storages.value.data.has('ABC')).toBe(false)
      expect(t.storages.stat.data.has('ABC')).toBe(false)
    })

    it('does not affect other entries', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      await cache.getOrCreate('key1', () => 'value1')
      await cache.getOrCreate('key2', () => 'value2')

      await cache.delete('key1')

      expect(t.storages.value.data.has('key1')).toBe(false)
      expect(t.storages.value.data.has('key2')).toBe(true)
      expect(t.storages.stat.data.has('key2')).toBe(true)

      // key2 still cached
      let callCount = 0
      const result = await cache.getOrCreate('key2', () => {
        callCount++
        return 'value2-new'
      })
      expect(result).toBe('value2')
      expect(callCount).toBe(0)
    })
  })

  describe('clear', () => {
    it('removes all entries', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      await cache.getOrCreate('key1', () => 'value1')
      await cache.getOrCreate('key2', () => 'value2')
      await expect(
        cache.getOrCreate('key3', () => {
          throw 'err'
        }),
      ).rejects.toBe('err')

      await cache.clear()

      expect(t.storages.value.data.size).toBe(0)
      expect(t.storages.error.data.size).toBe(0)
      expect(t.storages.stat.data.size).toBe(0)
    })

    it('after clear, getOrCreate re-computes all entries', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      await cache.getOrCreate('key1', () => 'value1')
      await cache.getOrCreate('key2', () => 'value2')
      await cache.clear()

      let callCount = 0
      const result1 = await cache.getOrCreate('key1', () => {
        callCount++
        return 'value1-new'
      })
      const result2 = await cache.getOrCreate('key2', () => {
        callCount++
        return 'value2-new'
      })
      expect(result1).toBe('value1-new')
      expect(result2).toBe('value2-new')
      expect(callCount).toBe(2)
    })
  })

  describe('concurrency', () => {
    it('serializes concurrent getOrCreate for same key', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      const callOrder: number[] = []
      let resolveFirst: (value: string) => void = null!

      const promise1 = cache.getOrCreate('key1', () => {
        callOrder.push(1)
        return new Promise<string>(resolve => {
          resolveFirst = resolve
        })
      })

      // Yield to allow the async lock handler chain to reach func()
      await waitMicrotasks()

      const promise2 = cache.getOrCreate('key1', () => {
        callOrder.push(2)
        return 'value2'
      })

      // Only first func called; second is queued behind the lock
      expect(callOrder).toEqual([1])

      resolveFirst('value1')
      const [result1, result2] = await Promise.all([promise1, promise2])

      // First creates value, second gets cached value (func not called)
      expect(result1).toBe('value1')
      expect(result2).toBe('value1')
      expect(callOrder).toEqual([1])
    })

    it('parallel getOrCreate for different keys runs concurrently', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      let key1Running = false
      let key2StartedWhileKey1Running = false

      const promise1 = cache.getOrCreate('key1', () => {
        key1Running = true
        return new Promise<string>(resolve => {
          setTimeout(() => {
            key1Running = false
            resolve('value1')
          }, 50)
        })
      })

      const promise2 = cache.getOrCreate('key2', () => {
        key2StartedWhileKey1Running = key1Running
        return 'value2'
      })

      const [result1, result2] = await Promise.all([promise1, promise2])
      expect(result1).toBe('value1')
      expect(result2).toBe('value2')
      expect(key2StartedWhileKey1Running).toBe(true)
    })

    it('concurrent getOrCreate with error and value for same key', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      let resolveError: () => void = null!

      const promise1 = cache.getOrCreate('key1', () => {
        return new Promise<string>((_, reject) => {
          resolveError = () => reject('first-error')
        })
      })

      // Yield to allow async chain to reach func()
      await waitMicrotasks()

      const promise2 = cache.getOrCreate('key1', () => {
        return 'value-from-second'
      })

      resolveError()

      await expect(promise1).rejects.toBe('first-error')
      // Second call gets cached error (serialized by lock)
      await expect(promise2).rejects.toBe('first-error')
    })

    it('delete serialized with getOrCreate for same key', async () => {
      const t = createTestOptions()
      const cache = createCache(t)

      let resolveFunc: (value: string) => void = null!

      // Start slow getOrCreate
      const getPromise = cache.getOrCreate('key1', () => {
        return new Promise<string>(resolve => {
          resolveFunc = resolve
        })
      })

      // Yield to allow async chain to reach func()
      await waitMicrotasks()

      // Queue delete behind getOrCreate
      const deletePromise = cache.delete('key1')

      resolveFunc('value1')
      await getPromise
      await deletePromise

      // After delete, key1 should be gone
      expect(t.storages.value.data.has('key1')).toBe(false)
      expect(t.storages.stat.data.has('key1')).toBe(false)

      // Re-computation works
      let callCount = 0
      const result = await cache.getOrCreate('key1', () => {
        callCount++
        return 'value1-recomputed'
      })
      expect(result).toBe('value1-recomputed')
      expect(callCount).toBe(1)
    })

    it('multiple concurrent getOrCreate for same key after expiration', async () => {
      const tc = new TimeControllerMock()
      tc.setTime(1000)
      const t = createTestOptions({
        timeController: tc,
        isExpired: stat => tc.now() - stat.dateModified > 500,
      })
      const cache = createCache(t)

      await cache.getOrCreate('key1', () => 'value1')

      tc.setTime(2000) // expired
      let resolveFunc: (value: string) => void = null!
      let callCount = 0

      const promise1 = cache.getOrCreate('key1', () => {
        callCount++
        return new Promise<string>(resolve => {
          resolveFunc = resolve
        })
      })

      // Flush microtasks with time controller context to reach func()
      await waitTimeControllerMock(tc)

      const promise2 = cache.getOrCreate('key1', () => {
        callCount++
        return 'value-from-second'
      })

      // Only first should be called at this point
      expect(callCount).toBe(1)

      resolveFunc('value-from-first')

      const [result1, result2] = await Promise.all([promise1, promise2])
      expect(result1).toBe('value-from-first')
      expect(result2).toBe('value-from-first')
      expect(callCount).toBe(1)
    })
  })

  describe('createFileCacheOptions integration', () => {
    beforeEach(async () => {
      await fs.promises.rm(DIR_TMP, { recursive: true }).catch(() => {})
      await fs.promises.mkdir(DIR_CACHE, { recursive: true })
      await fs.promises.mkdir(DIR_CACHE_TMP, { recursive: true })
    })

    afterEach(async () => {
      await fs.promises.rm(DIR_TMP, { recursive: true }).catch(() => {})
    })

    it('stores and retrieves values via filesystem', async () => {
      const options = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
      })
      const cache = new Cache(options)

      const result1 = await cache.getOrCreate('test-input', () => ({
        message: 'hello',
        count: 42,
      }))
      expect(result1).toEqual({ message: 'hello', count: 42 })

      // Retrieve from cache
      let callCount = 0
      const result2 = await cache.getOrCreate('test-input', () => {
        callCount++
        return { message: 'should not be called', count: 0 }
      })
      expect(result2).toEqual({ message: 'hello', count: 42 })
      expect(callCount).toBe(0)

      // Verify files exist on disk
      const cacheFiles = await readDirFlat(DIR_CACHE)
      expect(cacheFiles.length).toBeGreaterThan(0)
    })

    it('stores and retrieves errors via filesystem', async () => {
      const options = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
      })
      const cache = new Cache(options)

      const error = new Error('fs-cached-error')
      await expect(
        cache.getOrCreate('error-input', () => {
          throw error
        }),
      ).rejects.toThrow()

      // Second call returns cached error (converterErrorToBuffer serializes then deserializes)
      await expect(
        cache.getOrCreate('error-input', () => {
          return 'should not be called'
        }),
      ).rejects.toBeDefined()
    })

    it('respects totalSize with file storage', async () => {
      const options = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
        totalSize: [0, 500],
      })
      const cache = new Cache(options)

      for (let i = 0; i < 5; i++) {
        await cache.getOrCreate(`input-${i}`, () => ({
          data: 'x'.repeat(50),
          index: i,
        }))
      }

      const files1 = await readDirFlat(DIR_CACHE)
      expect(files1.length).toBe(5)

      // Store a large entry that triggers eviction
      await cache.getOrCreate('input-large', () => ({
        data: 'x'.repeat(200),
        index: 999,
      }))

      const files2 = await readDirFlat(DIR_CACHE)
      expect(files2.length).toBeLessThan(6)
    })

    it('persists cache across separate Cache instances', async () => {
      const makeOptions = () =>
        createFileCacheOptions({
          dir: DIR_CACHE,
          tmpDir: DIR_CACHE_TMP,
        })

      const cache1 = new Cache(makeOptions())
      await cache1.getOrCreate('persistent-key', () => ({
        persisted: true,
        value: 123,
      }))

      const cache2 = new Cache(makeOptions())
      let callCount = 0
      const result = await cache2.getOrCreate('persistent-key', () => {
        callCount++
        return { persisted: false, value: 0 }
      })
      expect(result).toEqual({ persisted: true, value: 123 })
      expect(callCount).toBe(0)
    })

    it('delete removes files from disk', async () => {
      const options = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
      })
      const cache = new Cache(options)

      await cache.getOrCreate('to-delete', () => ({ data: 'temp' }))
      const files1 = await readDirFlat(DIR_CACHE)
      expect(files1.length).toBeGreaterThan(0)

      await cache.delete('to-delete')

      let callCount = 0
      await cache.getOrCreate('to-delete', () => {
        callCount++
        return { data: 'recomputed' }
      })
      expect(callCount).toBe(1)
    })

    it('clear removes all files from disk', async () => {
      const options = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
      })
      const cache = new Cache(options)

      await cache.getOrCreate('key-a', () => 'value-a')
      await cache.getOrCreate('key-b', () => 'value-b')

      await cache.clear()

      let callCountA = 0
      let callCountB = 0
      await cache.getOrCreate('key-a', () => {
        callCountA++
        return 'value-a-new'
      })
      await cache.getOrCreate('key-b', () => {
        callCountB++
        return 'value-b-new'
      })
      expect(callCountA).toBe(1)
      expect(callCountB).toBe(1)
    })

    it('handles converterInput with getHashKey', async () => {
      const options = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
      })
      const cache = new Cache(options)

      // Different input objects with same content map to same cache key
      const result1 = await cache.getOrCreate(
        { a: 1, b: 2 } as any,
        () => 'value1',
      )

      let callCount = 0
      const result2 = await cache.getOrCreate({ a: 1, b: 2 } as any, () => {
        callCount++
        return 'value2'
      })
      expect(result1).toBe('value1')
      expect(result2).toBe('value1')
      expect(callCount).toBe(0)
    })

    it('isExpired works with file storage', async () => {
      const options = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
        isExpired: stat => Date.now() - stat.dateModified > 100,
      })
      const cache = new Cache(options)

      await cache.getOrCreate('expiring-key', () => 'original')

      const result1 = await cache.getOrCreate(
        'expiring-key',
        () => 'should-not-be-called',
      )
      expect(result1).toBe('original')

      await new Promise(resolve => setTimeout(resolve, 150))

      let callCount = 0
      const result2 = await cache.getOrCreate('expiring-key', () => {
        callCount++
        return 'recomputed'
      })
      expect(result2).toBe('recomputed')
      expect(callCount).toBe(1)
    })

    it('custom converterValue with file storage', async () => {
      const textEncoder = new TextEncoder()
      const textDecoder = new TextDecoder()
      const options = createFileCacheOptions<string, string>({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
        converterValue: {
          to: (value: string) => textEncoder.encode('custom:' + value),
          from: (stored: Uint8Array) =>
            textDecoder.decode(stored).replace('custom:', ''),
        },
      })
      const cache = new Cache(options)

      const result1 = await cache.getOrCreate('key1', () => 'hello')
      expect(result1).toBe('hello')

      const result2 = await cache.getOrCreate('key1', () => 'not-called')
      expect(result2).toBe('hello')
    })

    it('stores plain JSON bytes when compressOptions is not provided', async () => {
      const options = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
      })
      const cache = new Cache(options)

      const payload = { message: 'plain-json', count: 7 }
      await cache.getOrCreate('plain-key', () => payload)

      const valueFiles = (await readDirFlat(DIR_CACHE)).filter(f =>
        f.endsWith('.value'),
      )
      expect(valueFiles.length).toBe(1)
      const bytes = await fs.promises.readFile(valueFiles[0])
      expect(isGzipCompressed(bytes)).toBe(false)
      expect(JSON.parse(new TextDecoder().decode(bytes))).toEqual(payload)
    })

    it('stores plain JSON bytes when compressOptions is null', async () => {
      const options = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
        compressOptions: null,
      })
      const cache = new Cache(options)

      await cache.getOrCreate('null-key', () => ({ a: 1 }))

      const valueFiles = (await readDirFlat(DIR_CACHE)).filter(f =>
        f.endsWith('.value'),
      )
      const bytes = await fs.promises.readFile(valueFiles[0])
      expect(isGzipCompressed(bytes)).toBe(false)
    })

    it('stores gzip-compressed bytes when compressOptions is set', async () => {
      const options = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
        compressOptions: { level: 9 },
      })
      const cache = new Cache(options)

      const payload = { message: 'gzip-json', items: [1, 2, 3] }
      const result1 = await cache.getOrCreate('gzip-key', () => payload)
      expect(result1).toEqual(payload)

      const valueFiles = (await readDirFlat(DIR_CACHE)).filter(f =>
        f.endsWith('.value'),
      )
      expect(valueFiles.length).toBe(1)
      const bytes = await fs.promises.readFile(valueFiles[0])
      expect(isGzipCompressed(bytes)).toBe(true)

      const decompressed = await decompressGzip(bytes)
      expect(JSON.parse(new TextDecoder().decode(decompressed))).toEqual(
        payload,
      )

      let callCount = 0
      const result2 = await cache.getOrCreate('gzip-key', () => {
        callCount++
        return payload
      })
      expect(result2).toEqual(payload)
      expect(callCount).toBe(0)
    })

    it('stores gzip-compressed errors when compressOptions is set', async () => {
      const options = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
        compressOptions: { level: 9 },
      })
      const cache = new Cache(options)

      await expect(
        cache.getOrCreate('gzip-err-key', () => {
          throw new Error('gzip-cached-error')
        }),
      ).rejects.toThrow('gzip-cached-error')

      const errorFiles = (await readDirFlat(DIR_CACHE)).filter(f =>
        f.endsWith('.error'),
      )
      expect(errorFiles.length).toBe(1)
      const bytes = await fs.promises.readFile(errorFiles[0])
      expect(isGzipCompressed(bytes)).toBe(true)

      await expect(
        cache.getOrCreate('gzip-err-key', () => 'should-not-be-called'),
      ).rejects.toThrow('gzip-cached-error')
    })

    it('compressOptions reduces on-disk size for compressible data', async () => {
      const payload = { text: 'a'.repeat(10000) }

      const plainOptions = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
      })
      const plainCache = new Cache(plainOptions)
      await plainCache.getOrCreate('same-key', () => payload)
      const plainBytes = await fs.promises.readFile(
        (await readDirFlat(DIR_CACHE)).filter(f => f.endsWith('.value'))[0],
      )

      await fs.promises.rm(DIR_CACHE, { recursive: true })
      await fs.promises.mkdir(DIR_CACHE, { recursive: true })

      const gzipOptions = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
        compressOptions: { level: 9 },
      })
      const gzipCache = new Cache(gzipOptions)
      await gzipCache.getOrCreate('same-key', () => payload)
      const gzipBytes = await fs.promises.readFile(
        (await readDirFlat(DIR_CACHE)).filter(f => f.endsWith('.value'))[0],
      )

      expect(isGzipCompressed(plainBytes)).toBe(false)
      expect(isGzipCompressed(gzipBytes)).toBe(true)
      expect(gzipBytes.byteLength).toBeLessThan(plainBytes.byteLength)
    })

    it('compressOptions gzip persists across separate Cache instances', async () => {
      const makeOptions = () =>
        createFileCacheOptions({
          dir: DIR_CACHE,
          tmpDir: DIR_CACHE_TMP,
          compressOptions: { level: 6 },
        })

      const cache1 = new Cache(makeOptions())
      const payload = { persisted: true, items: ['x', 'y', 'z'] }
      await cache1.getOrCreate('persistent-gzip-key', () => payload)

      const cache2 = new Cache(makeOptions())
      let callCount = 0
      const result = await cache2.getOrCreate('persistent-gzip-key', () => {
        callCount++
        return { persisted: false, items: [] }
      })
      expect(result).toEqual(payload)
      expect(callCount).toBe(0)
    })

    it('compressOptions level 0 still produces gzip wrapper', async () => {
      const options = createFileCacheOptions({
        dir: DIR_CACHE,
        tmpDir: DIR_CACHE_TMP,
        compressOptions: { level: 0 },
      })
      const cache = new Cache(options)

      const payload = { message: 'level-zero' }
      const result1 = await cache.getOrCreate('level0-key', () => payload)
      expect(result1).toEqual(payload)

      const valueFiles = (await readDirFlat(DIR_CACHE)).filter(f =>
        f.endsWith('.value'),
      )
      const bytes = await fs.promises.readFile(valueFiles[0])
      expect(isGzipCompressed(bytes)).toBe(true)

      const result2 = await cache.getOrCreate('level0-key', () => payload)
      expect(result2).toEqual(payload)
    })
  })
})

// Helpers

class MemoryStorage<Key, Value> implements IStorage<Key, Value> {
  readonly data: Map<Key, Value> = new Map()

  async set(key: Key, value: Value): Promise<void> {
    this.data.set(key, value)
  }

  async get(key: Key): Promise<Value | undefined> {
    return this.data.get(key)
  }

  async delete(key: Key): Promise<void> {
    this.data.delete(key)
  }

  async getKeys(): Promise<Key[]> {
    return Array.from(this.data.keys())
  }
}

class MemoryStorageDb<Key, Value>
  extends MemoryStorage<Key, Value>
  implements IStorageDb<Key, Value>
{
  async getEntries(): Promise<ReadonlyMap<Key, Value>> {
    return new Map(this.data)
  }
}

type TestStorages = {
  value: MemoryStorage<string, string>
  error: MemoryStorage<string, string>
  stat: MemoryStorageDb<string, CacheStat>
}

function createTestOptions(options?: {
  totalSize?: null | NumberRange
  isExpired?: null | ((stat: CacheStat) => boolean)
  timeController?: null | TimeControllerMock
}): {
  options: CacheOptions<
    string,
    string,
    string,
    CacheStat,
    string,
    string,
    string,
    CacheStat
  >
  storages: TestStorages
} {
  const storages: TestStorages = {
    value: new MemoryStorage(),
    error: new MemoryStorage(),
    stat: new MemoryStorageDb(),
  }
  return {
    storages,
    options: {
      storages,
      totalSize: options?.totalSize,
      getSize: {
        value: (value: string) => value.length,
        error: (error: string) => error.length,
        stat: () => 1,
      },
      isExpired: options?.isExpired,
      timeController: options?.timeController,
    },
  }
}

function createCache(t: ReturnType<typeof createTestOptions>) {
  return new Cache(t.options)
}

async function readDirFlat(dir: string): Promise<string[]> {
  const result: string[] = []
  try {
    const entries = await fs.promises.readdir(dir, { withFileTypes: true })
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        const nested = await readDirFlat(fullPath)
        result.push(...nested)
      } else {
        result.push(fullPath)
      }
    }
  } catch (err: any) {
    if (err.code === 'ENOENT') {
      return []
    }
    throw err
  }
  return result
}
